master: split build command to avoid breakage
I’m not entirely sure why, but build fails when building all the
packages together:

    cargo build -p neard -p genesis-populate -p restaked \
                -p near-test-contracts --features adversarial \
                --features nightly_protocol,nightly_protocol_features
    […]
    error[E0063]: missing field `evm_chain_id` in initializer of `ApplyState`
       --> test-utils/testlib/src/user/runtime_user.rs:131:9
        |
    131 |         ApplyState {
        |         ^^^^^^^^^^ missing `evm_chain_id`

    error[E0063]: missing field `evm_chain_id` in initializer of `ViewApplyState`
       --> test-utils/testlib/src/user/runtime_user.rs:246:26
        |
    246 |         let view_state = ViewApplyState {
        |                          ^^^^^^^^^^^^^^ missing `evm_chain_id`

    error: aborting due to 2 previous errors

However, things work fine if `neard` is built separately from the
other packages.  It has to do with `protocol_feature_evm` which is not
enabled in `testlib` when necessary.  Whatever the case may be, split
the build into two commands.

Fixes: https://github.com/near/nayduck/issues/3